name=Vira WiFi Manager
version=2.0.0
author=Mostafa MirMousavi
maintainer=Mostafa MirMousavi <aloneroot@gmail.com>
sentence=Advanced WiFi Manager for ESP8266 and ESP32 with Captive Portal, Static IP, Gateway and Subnet configuration.
paragraph=Vira WiFi Manager (ViraWM) is an advanced WiFi configuration library for ESP8266 and ESP32 based on the original WiFiManager project, redesigned and enhanced with modern features including Captive Portal, Automatic WiFi Connection, Static IP, Gateway, Subnet Mask, WiFi Profile Management, Factory Reset, Custom Parameters and an improved user experience. Designed and Maintained by Mostafa MirMousavi (ViraMedar).
category=Communication
url=https://github.com/admin3314/Vira_WiFi_Manager
architectures=esp8266,esp32
includes=ViraWM.h
license=MIT